# Variables
CC = gcc
CFLAGS = -Wall -Wextra -g
OBJ = main.o algorithme_recherche_naif.o morris_pratt.o
TARGET = programme_recherche
# Règle par défaut
all: $(TARGET) 

# Compilation du programme
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJ)

# Compilation des fichiers objets
main.o: main.c algorithme_recherche_naif.h
	$(CC) $(CFLAGS) -c main.c 
morris_pratt.o: morris_pratt.c morris_pratt.h
	$(CC) $(CFLAGS) -c morris_pratt.c
algorithme_recherche_naif.o: algorithme_recherche_naif.c algorithme_recherche_naif.h
	$(CC) $(CFLAGS) -c algorithme_recherche_naif.c

# Nettoyage des fichiers objets et exécutables
clean:
	rm -f $(OBJ) $(TARGET)

# Règle pour nettoyer tout
distclean: clean
	rm -f $(TARGET)
